language: node_js
matrix:
 include:
  - node_js: "stable"
    env: GULP_TASK="test-functional-local"
    os: osx
    osx_image: xcode8
 fast_finish: true

branches:
  except:
    - /^build-bot-temp-.*$/

notifications:
 email: false
