addons:
 chrome:  stable
 firefox: latest
 apt:
  packages:
   - dbus

language: node_js
matrix:
 include:
  - node_js: "stable"
    env: GULP_TASK="test-client-travis"

 fast_finish: true

cache: yarn

before_install:
  - export $(dbus-launch)
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install: yarn

branches:
  except:
    - /^build-bot-temp-.*$/

notifications:
 email: false
