version: "#{build}"
clone_depth: 1

skip_commits:
  message: /^\[docs\]/

environment:
  GULP_TASK: "test-functional-local"
  NODEJS_VERSION: "stable"

install:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
- ps: >-
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))

    Set-ScreenResolution 1920 1080

    Install-Product node $env:NODEJS_VERSION

    choco install GoogleChrome | out-null

    choco install Firefox | out-null

- cmd: >-
    node --version

    npm --version

    npm install

build: off

test_script:
- cmd: npm test
