version: "#{build}"
clone_depth: 1

skip_commits:
  message: /^\[docs\]/

environment:
  NODEJS_VERSION: "stable"

  matrix:
    - GULP_TASK: "test-functional-local-ie"

init:
 - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

for:
-
  branches:
    only:
      - master

  notifications:
  - provider: Email
    to:
    - boris.kirov@devexpress.com
    - andrey.belym@devexpress.com
    - elena.dikareva@devexpress.com
    on_build_success: false
    on_build_status_changed: false

  environment:
    matrix:
    - GULP_TASK: "test-functional-local-chrome-firefox"
    - GULP_TASK: "test-functional-local-legacy"

install:
- ps: >-
    iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/set-screenresolution.ps1'))

    Set-ScreenResolution 1920 1080

    Install-Product node $env:NODEJS_VERSION

    choco install GoogleChrome | out-null

    choco install Firefox | out-null

    npm --version

    npm i --loglevel error
build: off

test_script:
- cmd: npm test
